In [24]:
import pandas as pd
import geopandas as gpd
import os
import folium
from opencage.geocoder import OpenCageGeocode

In [25]:
#Update the Database with relative paths
current_dir = os.getcwd()
CriminalData= pd.read_csv(os.path.join(current_dir, 'CriminalDataSetIndia.csv'))

In [26]:
CriminalData

,S.No,City,2019,2020,2021,Population,RateofCognizableCrimes,ChargesSheetingRate
0,1,Agra,6510,6285,5665,17.5,324.5,58.0
1,2,Allahabad,5621,5455,4130,12.2,339.4,68.2
2,3,Amritsar,2589,3178,3349,11.8,282.9,54.8
3,4,Asansol,4244,4335,4864,12.4,391.3,95.8
4,5,Aurangabad,5636,6248,7366,11.9,619.5,82.6
5,6,Bhopal,15367,18329,18831,18.8,1000.1,88.3
6,7,Chandigarh City,2819,2583,2401,10.3,234.0,67.7
7,8,Dhanbad,2102,2801,2508,11.9,209.9,36.0
8,9,Durg-Bhilainagar,5334,5199,5454,10.6,512.6,85.1
9,10,Faridabad,11717,9313,9771,14.1,695.4,56.8
10,11,Gwalior,9192,8920,10043,11.0,911.3,75.0
11,12,Jabalpur,7927,8707,12200,12.7,962.1,92.5
12,13,Jamshedpur,2831,2828,2965,13.4,221.8,60.4
13,14,Jodhpur,7597,5860,6882,11.4,604.7,47.6
14,15,Kannur,1534,1241,3034,16.4,184.7,90.7
15,16,Kollam,7272,7089,5113,11.1,460.6,85.1
16,17,Kota,5718,4454,4717,10.0,471.2,52.9
17,18,Ludhiana,5230,4808,5706,16.1,353.5,59.2
18,19,Madurai,3653,16196,6277,14.6,429.3,10.0
19,20,Malappuram,2086,1883,2016,17.0,118.7,90.7
20,21,Meerut,6500,7477,5501,14.3,386.0,70.1
21,22,Nasik,6025,4641,3032,15.6,194.0,65.6
22,23,Raipur,6001,5992,5910,11.2,526.3,76.6
23,24,Rajkot,2226,24140,32104,13.9,2308.0,99.3
24,25,Ranchi,3753,3443,3705,11.3,328.7,80.7
25,26,Srinagar,2215,2585,2833,12.7,222.5,76.3
26,27,Thiruvananthapuram,22248,11862,5707,16.9,338.3,95.5
27,28,Thrissur,6615,6606,7131,18.5,384.4,89.8
28,29,Tiruchirapalli,2387,7258,2604,10.2,254.8,82.3
29,30,Vadodara,4521,13517,8181,18.2,450.2,91.9
30,31,Varanasi,6989,5746,5720,14.4,398.6,76.6
31,32,Vasai Virar,4617,4143,5132,12.2,420.3,52.2
32,33,Vijayawada,6206,8352,9710,14.9,651.2,94.9
33,34,Vishakhapatnam,6329,11418,11590,17.3,669.9,93.3

In [27]:
#Opencage API Key
api_key = '345da8ea035c4f6490f6bd652d926602'

In [28]:
#Add the", India" to the end of the City to get the correct location
CriminalData['City'] = CriminalData['City'] + ', India'
CriminalData

,S.No,City,2019,2020,2021,Population,RateofCognizableCrimes,ChargesSheetingRate
0,1,"Agra, India",6510,6285,5665,17.5,324.5,58.0
1,2,"Allahabad, India",5621,5455,4130,12.2,339.4,68.2
2,3,"Amritsar, India",2589,3178,3349,11.8,282.9,54.8
3,4,"Asansol, India",4244,4335,4864,12.4,391.3,95.8
4,5,"Aurangabad, India",5636,6248,7366,11.9,619.5,82.6
5,6,"Bhopal, India",15367,18329,18831,18.8,1000.1,88.3
6,7,"Chandigarh City, India",2819,2583,2401,10.3,234.0,67.7
7,8,"Dhanbad, India",2102,2801,2508,11.9,209.9,36.0
8,9,"Durg-Bhilainagar, India",5334,5199,5454,10.6,512.6,85.1
9,10,"Faridabad, India",11717,9313,9771,14.1,695.4,56.8
10,11,"Gwalior, India",9192,8920,10043,11.0,911.3,75.0
11,12,"Jabalpur, India",7927,8707,12200,12.7,962.1,92.5
12,13,"Jamshedpur, India",2831,2828,2965,13.4,221.8,60.4
13,14,"Jodhpur, India",7597,5860,6882,11.4,604.7,47.6
14,15,"Kannur, India",1534,1241,3034,16.4,184.7,90.7
15,16,"Kollam, India",7272,7089,5113,11.1,460.6,85.1
16,17,"Kota, India",5718,4454,4717,10.0,471.2,52.9
17,18,"Ludhiana, India",5230,4808,5706,16.1,353.5,59.2
18,19,"Madurai, India",3653,16196,6277,14.6,429.3,10.0
19,20,"Malappuram, India",2086,1883,2016,17.0,118.7,90.7
20,21,"Meerut, India",6500,7477,5501,14.3,386.0,70.1
21,22,"Nasik, India",6025,4641,3032,15.6,194.0,65.6
22,23,"Raipur, India",6001,5992,5910,11.2,526.3,76.6
23,24,"Rajkot, India",2226,24140,32104,13.9,2308.0,99.3
24,25,"Ranchi, India",3753,3443,3705,11.3,328.7,80.7
25,26,"Srinagar, India",2215,2585,2833,12.7,222.5,76.3
26,27,"Thiruvananthapuram, India",22248,11862,5707,16.9,338.3,95.5
27,28,"Thrissur, India",6615,6606,7131,18.5,384.4,89.8
28,29,"Tiruchirapalli, India",2387,7258,2604,10.2,254.8,82.3
29,30,"Vadodara, India",4521,13517,8181,18.2,450.2,91.9
30,31,"Varanasi, India",6989,5746,5720,14.4,398.6,76.6
31,32,"Vasai Virar, India",4617,4143,5132,12.2,420.3,52.2
32,33,"Vijayawada, India",6206,8352,9710,14.9,651.2,94.9
33,34,"Vishakhapatnam, India",6329,11418,11590,17.3,669.9,93.3

In [29]:
Cities = CriminalData['City'].unique()

#Get the coordinates for the cities
geocoder = OpenCageGeocode(api_key)

#Get the coordinates for the unique location
coordinates = []
for location in Cities:
    results = geocoder.geocode(location)
    if results and len(results):
        coordinates.append(results[0]['geometry'])
    else:
        coordinates.append(None)

#Create a dataframe with the coordinates
coordinates_df = pd.DataFrame(coordinates)

#Add the coordinates to the cities
Cities = pd.DataFrame(Cities, columns=['City'])
Cities = pd.concat([Cities, coordinates_df], axis=1)
Cities

                         City        lat        lng
0                 Agra, India  27.175255  78.009816
1            Allahabad, India  25.438130  81.833800
2             Amritsar, India  31.634308  74.873679
3              Asansol, India  23.687130  86.974659
4           Aurangabad, India  24.786306  84.414490
5               Bhopal, India  23.258486  77.401989
6      Chandigarh City, India  30.748224  76.786938
7              Dhanbad, India  23.795281  86.430964
8     Durg-Bhilainagar, India  22.000000  79.000000
9            Faridabad, India  28.403148  77.310556
10             Gwalior, India  26.203725  78.157363
11            Jabalpur, India  23.160894  79.949770
12          Jamshedpur, India  22.801519  86.202958
13             Jodhpur, India  26.296772  73.035143
14              Kannur, India  11.876384  75.373797
15              Kollam, India   8.887951  76.595501
16                Kota, India  25.173702  75.857419
17            Ludhiana, India  30.909016  75.851601
18             Madurai, India   9.926115  78.114098
19          Malappuram, India  11.042893  76.080784
20              Meerut, India  28.982653  77.708101
21               Nasik, India  20.011247  73.790236
22              Raipur, India  21.238091  81.633699
23              Rajkot, India  22.305326  70.802838
24              Ranchi, India  23.370050  85.325039
25            Srinagar, India  34.074744  74.820444
26  Thiruvananthapuram, India   8.488227  76.947551
27            Thrissur, India  10.527010  76.214621
28      Tiruchirapalli, India  10.763165  78.713260
29            Vadodara, India  22.297314  73.194257
30            Varanasi, India  25.335649  83.007629
31         Vasai Virar, India  19.421042  72.819722
32          Vijayawada, India  16.508757  80.618509
33      Vishakhapatnam, India  17.680090  83.201610

In [30]:
#Add RateofRecognizableCrimes from the CriminalData to the Cities
CriminalCities = pd.merge(Cities, CriminalData[['City', 'RateofCognizableCrimes']], on='City')
CriminalCities

                         City        lat        lng  RateofCognizableCrimes
0                 Agra, India  27.175255  78.009816                   324.5
1            Allahabad, India  25.438130  81.833800                   339.4
2             Amritsar, India  31.634308  74.873679                   282.9
3              Asansol, India  23.687130  86.974659                   391.3
4           Aurangabad, India  24.786306  84.414490                   619.5
5               Bhopal, India  23.258486  77.401989                  1000.1
6      Chandigarh City, India  30.748224  76.786938                   234.0
7              Dhanbad, India  23.795281  86.430964                   209.9
8     Durg-Bhilainagar, India  22.000000  79.000000                   512.6
9            Faridabad, India  28.403148  77.310556                   695.4
10             Gwalior, India  26.203725  78.157363                   911.3
11            Jabalpur, India  23.160894  79.949770                   962.1
12          Jamshedpur, India  22.801519  86.202958                   221.8
13             Jodhpur, India  26.296772  73.035143                   604.7
14              Kannur, India  11.876384  75.373797                   184.7
15              Kollam, India   8.887951  76.595501                   460.6
16                Kota, India  25.173702  75.857419                   471.2
17            Ludhiana, India  30.909016  75.851601                   353.5
18             Madurai, India   9.926115  78.114098                   429.3
19          Malappuram, India  11.042893  76.080784                   118.7
20              Meerut, India  28.982653  77.708101                   386.0
21               Nasik, India  20.011247  73.790236                   194.0
22              Raipur, India  21.238091  81.633699                   526.3
23              Rajkot, India  22.305326  70.802838                  2308.0
24              Ranchi, India  23.370050  85.325039                   328.7
25            Srinagar, India  34.074744  74.820444                   222.5
26  Thiruvananthapuram, India   8.488227  76.947551                   338.3
27            Thrissur, India  10.527010  76.214621                   384.4
28      Tiruchirapalli, India  10.763165  78.713260                   254.8
29            Vadodara, India  22.297314  73.194257                   450.2
30            Varanasi, India  25.335649  83.007629                   398.6
31         Vasai Virar, India  19.421042  72.819722                   420.3
32          Vijayawada, India  16.508757  80.618509                   651.2
33      Vishakhapatnam, India  17.680090  83.201610                   669.9

In [31]:
#Save the data to a csv file
CriminalCities.to_csv('CriminalCities.csv', index=False)

In [32]:
import folium
from folium.plugins import HeatMap

# Create a map centered on India
CriminalMapIndia = folium.Map(location=[20.5937, 78.9629], zoom_start=5)

# Create a heat map layer using the CriminalCities dataframe
heat_data = [[row['lat'], row['lng'], row['RateofCognizableCrimes']] for index, row in CriminalCities.iterrows()]
HeatMap(heat_data).add_to(CriminalMapIndia)

#Reducce the Map Size
CriminalMapIndia.fit_bounds(CriminalMapIndia.get_bounds())

# Display the map
CriminalMapIndia

In [33]:
#Save the map
CriminalMapIndia.save('CriminalMapIndia.html')